#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:a100
#SBATCH --job-name=comp3710
#SBATCH --output=stdout.log       # Redirect stdout to stdout.log
#SBATCH --error=stderr.log        # Redirect stderr to stderr.log

conda activate torch
python generative.py